require 'veritas/algebra/binary_operation'
require 'veritas/algebra/combine_operation'
require 'veritas/algebra/set_operation'

require 'veritas/algebra/difference'
require 'veritas/algebra/intersection'
require 'veritas/algebra/join'
require 'veritas/algebra/product'
require 'veritas/algebra/project'
require 'veritas/algebra/rename'
require 'veritas/algebra/restriction'
require 'veritas/algebra/union'
