require 'veritas/optimizer/algebra/difference'
require 'veritas/optimizer/algebra/intersection'
require 'veritas/optimizer/algebra/join'
require 'veritas/optimizer/algebra/product'
require 'veritas/optimizer/algebra/projection'
require 'veritas/optimizer/algebra/rename'
require 'veritas/optimizer/algebra/restriction'
require 'veritas/optimizer/algebra/union'
